### PR TITLE
Travis CI 

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by dylanstrategie** [comment]
Gonna have to compile before we merge it, of course

**Comment by PJB3005** [comment]
Yeah of course but Unity is fucking broken and tries to connect to X even in batchmode.

And it's been broken for 5 fucking years.

God. Fucking. Damnit.

**Comment by dylanstrategie** [comment]
Well, I'll let you try and figure it out on your side, I suppose

As long as it doesn't compile, I can't really merge it anyways

**Comment by PJB3005** [comment]
Welp we're going back to takes-hours-to-start-a-build-OSX

**Comment by PJB3005** [comment]
Okay so I'm on OSX...

`Building a player for 'Mac' (2) target is not supported in this Unity build.`

I'm done. Fuck this horribly useless platform.

**Comment by dylanstrategie** [comment]
Unity supports Mac, does it not ?

Might want to forward this question directly to Unity forums

**Comment by PJB3005** [comment]
Yes, it does.

So the issue is the Unity installer seperates the target platforms into modules, but I can't find how to install the modules through the command line.

And I can't fucking sign in to the unity forums, it just doesn't work for me.

**Comment by PJB3005** [comment]
Fucking finally I got it to work.

**Comment by dylanstrategie** [comment]
Well then, the work time is high, but it's certainly good. Are we ready to go for a merge ?

**Comment by dylanstrategie** [comment]
Got the call

**Comment by PJB3005** [comment]
Did you really just not squash merge my 23 commit mess?

**Comment by dylanstrategie** [comment]
Shrug

**Pull request merged**
