### PR TITLE
Clean up a bit of AccessSystem.cs

### PR DESCRIPTION
**Pull request by PJB3005**
~~Note: untested.~~

~~@UristMcDorf tell me how I should test this.~~

### CODE REVIEW

**Comment by PJB3005** [comment]
Build is failing because there's no travis file yet.

#4 will have to be merged.

**Comment by dylanstrategie** [comment]
Done and done

**Comment by UristMcDorf** [comment]
PJB - check the initial commit for AccessSystem.cs and all that. Basically - spawn PDA, spawn ID reader, connect that to light, use anything other than PDA on ID reader, use PDA on ID reader.

**Comment by PJB3005** [comment]
Alright it works.

**Comment by dylanstrategie** [comment]
Merge it is then

**Pull request merged**
